# -*- coding: utf-8 -*-
"""sitemap-export

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WRVkZRMvIV0NXXwvq3KhazbW9RTjtu-N
"""

import requests
import pandas as pd
from bs4 import BeautifulSoup
from urllib.parse import urljoin

def extract_sitemap_links(url):
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')

    sitemap_links = []

    # Look for <sitemap> tags
    for loc in soup.find_all('sitemap'):
        sitemap_links.append(loc.find('loc').text)

    # Look for <url> tags
    for loc in soup.find_all('url'):
        loc_text = loc.find('loc').text
        if loc_text.endswith('.xml'):
            sitemap_links.append(loc_text)

    return sitemap_links

def save_to_csv(links):
    df = pd.DataFrame(links, columns=['Sitemap Links'])
    df.to_csv('sitemap_links.csv', index=False)
    print('Sitemap links saved to sitemap_links.csv')

if __name__ == '__main__':
    website_url = input('Enter the website URL to extract sitemap links: ')
    sitemap_links = extract_sitemap_links(website_url)
    save_to_csv(sitemap_links)